#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  shift; shift

  local tmp_config="$(mktemp -t XXXXXX.json)"
  trap "$(printf 'rm -f %q' "$tmp_config")" EXIT 

  local pth_themes="${BOARD_PATH}/themes"
  if [[ -d "$phome/themes" ]]; then
    pth_themes="$phome/themes"
  fi

  if [[ "$#" == 0 ]]; then
    set -- "$phome"
  fi

  for phome in "$@"; do
    jq -n -r \
      --argfile seed "${BOARD_PATH}/config.json" \
      --argfile content "$phome/config.json" \
      '$seed * $content' > "$tmp_config"

    rm -rf "$phome/.public"
    hugo --config "$tmp_config" --contentDir "$phome/content/"  --themesDir "$pth_themes"
  done
}

source sub "$0" "$@"
