#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  shift; shift

  local tmp_config="$(mktemp -t XXXXXX.json)"
  trap "$(printf 'rm -f %q' "$tmp_config")" EXIT 

  jq -n -r \
    --argfile seed "${BOARD_PATH}/config.json" \
    --argfile content "$phome/config.json" \
    '$seed * $content' > "$tmp_config"

  cd "$BOARD_PATH"
  hugo --config "$tmp_config" --contentDir "$phome/content/" 
}

source sub "$0" "$@"
