#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  mkdir -p "$shome/bin"

  block compile pipenv
  ln -nfs $(pipenv run which pycco pygmentize) "$shome/bin/"

  block compile yarn
  ln -nfs ../node_modules/.bin/prettier "$shome/bin/"
  ln -nfs ../node_modules/.bin/http-server "$shome/bin/"
}

bootstrap
