#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv
  ln -nfs ../vendor/virtualenv/bin/pygmentize bin/
  ln -nfs ../vendor/virtualenv/bin/pycco bin/
}

bootstrap
