#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P pycco >/dev/null; then
    return 1
  fi

  if ! type -P prettier >/dev/null; then
    return 1
  fi

  if ! type -P http-server >/dev/null; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
